### ISSUE TITLE
Ordainketak egiteko eguna hartu.

### ISSUE THREAD

**Issue by ghost** [igorosabel/Coffee#1]
Kaixo,

Ordainketa egiteko eguna hartzea ondo egongo zen.

Eskerrik asko.

**Comment by igorosabel** [comment]
Ados, hurrengo bertsiorako

**Comment by igorosabel** [comment]
Dagoeneko aukeratu daiteke nor ordaintzen duen edozein egunetan, beraz eginda egongo zen :)
